apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        cpaas.io/creator: k00395
        kubernetes.io/ingress.class: ""
        ncp/internal_ip_for_policy: 100.64.145.41
        ncp/use-regex: "true"
    labels:
        cpaasAutoDeploy: "10"
    name: iomp-demo
    namespace: iomp-d
spec:
    rules:
        - host: iomp.acp.td.io
          http:
            paths:
                - backend:
                    serviceName: nginx-test-nginx
                    servicePort: 8081
                  path: /.*
