apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: nginx.iomp-s1
        cpaasAutoDeploy: "10"
    name: nginx-test-nginx
    namespace: iomp-s1
spec:
    replicas: 2
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-nginx-test-nginx
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                app: deployment-nginx-test-nginx
                app.cpaas.io/name: nginx.iomp-s1
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-nginx-test-nginx
                version: v1
        spec:
            containers:
                - image: harbor.ms.io/iomp-s1/test-nginx:latest
                  imagePullPolicy: IfNotPresent
                  name: test-nginx
                  resources:
                    limits:
                        cpu: "1"
                        memory: 2G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
