apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    finalizers:
        - kubernetes.io/pvc-protection
    labels:
        cpaasAutoDeploy: "10"
    name: iomp-ftp-d-consul-pvc
    namespace: iomp-ftp-d
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 8G
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: iomp-ftp-d-consul-pv
