apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        cpaas.io/creator: k00297
        kubernetes.io/ingress.class: ""
        ncp/internal_ip_for_policy: 100.64.130.137
        ncp/use-regex: "true"
    labels:
        cpaasAutoDeploy: "10"
    name: ftp-domain
    namespace: iomp-ftp-s1
spec:
    rules:
        - host: iomp-ftp.ms1.io
          http:
            paths:
                - backend:
                    serviceName: ftp-ui-ftp-ui
                    servicePort: 8081
                  path: /.*
