apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: process.iomp-p
        cpaasAutoDeploy: "10"
        jmx-monitor: app-jmx-monitor
        poin-monitor: app-poin-monitor
    name: process-iomp-process
    namespace: iomp-p
spec:
    ports:
        - name: tcp-18099-18099
          port: 18099
          protocol: TCP
          targetPort: 18099
        - name: tcp-8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: tcp-18080-18080
          port: 18080
          protocol: TCP
          targetPort: 18080
        - name: tcp-9091-9091
          port: 9091
          protocol: TCP
          targetPort: 9091
    selector:
        service.cpaas.io/name: deployment-process-iomp-process
    sessionAffinity: None
    type: ClusterIP
