apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: poin-manage-center.iomp-s1
        cpaasAutoDeploy: "10"
    name: iomp-s1-poincenter
    namespace: iomp-s1
spec:
    ports:
        - name: 8033-8033
          port: 8033
          protocol: TCP
          targetPort: 8033
        - name: 9090-9090
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: 9411-9411
          port: 9411
          protocol: TCP
          targetPort: 9411
        - name: 8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: 8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: 8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: 8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: 8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: 8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: 8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: 10007-10007
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: 10008-10008
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        service.cpaas.io/name: deployment-poin-manage-center-iomp-s1-poincenter
    sessionAffinity: None
    type: ClusterIP
