apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: nginx.iomp-s1
        cpaasAutoDeploy: "10"
    name: nginx-test-nginx
    namespace: iomp-s1
spec:
    ports:
        - name: tcp-9931-9931
          port: 9931
          protocol: TCP
          targetPort: 9931
        - name: tcp-8081-8081
          port: 8081
          protocol: TCP
          targetPort: 8081
    selector:
        service.cpaas.io/name: deployment-nginx-test-nginx
    sessionAffinity: None
    type: ClusterIP
