apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
        ncp/internal_ip_for_policy: 100.64.80.49
    labels:
        cpaasAutoDeploy: "10"
        poin-monitor: app-poin-monitor
    name: poin-gateway-lb
    namespace: iomp-s1
spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: l4lb-s1d-devk8s-acp-iomp-s1-gateway-108.188-ippool
    ports:
        - name: tcp-9090-9090
          nodePort: 30315
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: tcp-8500-8500
          nodePort: 30885
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          nodePort: 31166
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          nodePort: 31683
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8600-8600
          nodePort: 30139
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: tcp-8300-8300
          nodePort: 30019
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          nodePort: 31326
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          nodePort: 32524
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-10007-10007
          nodePort: 31549
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: tcp-10008-10008
          nodePort: 31619
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        service.cpaas.io/name: deployment-poin-gateway-iomp-s1-gateway
    sessionAffinity: None
    type: LoadBalancer
