apiVersion: v1
kind: Service
metadata:
    annotations:
        ncp/internal_ip_for_policy: 100.64.80.49
    labels:
        cpaasAutoDeploy: "10"
        poin-monitor: app-poin-monitor
    name: poin-gateway-lb
    namespace: iomp-d
spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: l4lb-td-devk8s-acp-iomp-d-gateway-108.175-ippool
    ports:
        - name: tcp-9090-9090
          nodePort: 30867
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: tcp-8500-8500
          nodePort: 32349
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          nodePort: 30003
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          nodePort: 31668
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8600-8600
          nodePort: 31573
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: tcp-8300-8300
          nodePort: 31554
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          nodePort: 30445
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          nodePort: 30074
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-10007-10007
          nodePort: 32377
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: tcp-10008-10008
          nodePort: 31395
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        service.cpaas.io/name: deployment-poin-gateway-iomp-d-gateway
    sessionAffinity: None
    type: LoadBalancer
