apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        BUILD_ID: "10"
        JOB_BASE_NAME: iomp-gateway-deploy-test
        app.cpaas.io/name: poin-gateway.iomp-s1
        cpaasAutoDeploy: "10"
    name: poin-gateway-iomp-s1-gateway
    namespace: iomp-s1
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-poin-gateway-iomp-s1-gateway
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                BUILD_ID: "10"
                JOB_BASE_NAME: iomp-gateway-deploy-test
                app: deployment-poin-gateway-iomp-s1-gateway
                app.cpaas.io/name: poin-gateway.iomp-s1
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-poin-gateway-iomp-s1-gateway
                version: v1
        spec:
            containers:
                - env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: ACTIVE_PROFILES
                      value: test
                  image: harbor.td.io/iomp-s1/iomp-s1-gateway:latest
                  imagePullPolicy: Always
                  name: iomp-s1-gateway
                  resources:
                    limits:
                        cpu: "1"
                        memory: 2Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-s1-consul register-c2-s1-consul register-c3-s1-consul
                  image: harbor.td.io/common-s1/t-consul:20200721_01
                  imagePullPolicy: IfNotPresent
                  name: t-consul
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
                - name: dockercfg--iomp--iomp-harbor-devops-copy
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: poin-gateway.iomp-s1
        cpaasAutoDeploy: "10"
    name: poin-gateway
    namespace: iomp-s1
spec:
    ports:
        - name: tcp-8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-9090-9090
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: tcp-8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: tcp-8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-10007-10007
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: tcp-10008-10008
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        service.cpaas.io/name: deployment-poin-gateway-iomp-s1-gateway
    sessionAffinity: None
    type: ClusterIP
