apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00297
    labels:
        app.cpaas.io/name: ftp-zipkin.iomp-ftp-s1
        cpaasAutoDeploy: "10"
    name: ftp-zipkin-zipkin-ftp
    namespace: iomp-ftp-s1
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-ftp-zipkin-zipkin-ftp
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00297
            labels:
                app: deployment-ftp-zipkin-zipkin-ftp
                app.cpaas.io/name: ftp-zipkin.iomp-ftp-s1
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-ftp-zipkin-zipkin-ftp
                version: v1
        spec:
            containers:
                - image: harbor.ms.io/iomp-s1/zipkin-ftp:20201103_01
                  imagePullPolicy: IfNotPresent
                  name: zipkin-ftp
                  resources:
                    limits:
                        cpu: "4"
                        memory: 4Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /jdk8/application.properties
                      name: zipkin-volume
                      subPath: application.properties
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: as-register-c1-s1-consul as-register-c2-s1-consul as-register-c3-s1-consul
                  image: harbor.ms.io/common-s1/s1-consul:20200831_01
                  imagePullPolicy: IfNotPresent
                  name: s1-consul
                  resources:
                    limits:
                        cpu: 500m
                        memory: 512Mi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - configMap:
                    defaultMode: 420
                    name: zipkin-application
                  name: zipkin-volume
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00297
    labels:
        app.cpaas.io/name: ftp-zipkin.iomp-ftp-s1
        cpaasAutoDeploy: "10"
    name: ftp-zipkin
    namespace: iomp-ftp-s1
spec:
    ports:
        - name: tcp-19411-19411
          port: 19411
          protocol: TCP
          targetPort: 19411
        - name: tcp-8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
    selector:
        service.cpaas.io/name: deployment-ftp-zipkin-zipkin-ftp
    sessionAffinity: None
    type: ClusterIP
