apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    finalizers:
        - kubernetes.io/pvc-protection
    labels:
        cpaasAutoDeploy: "10"
    name: consul-tev
    namespace: iomp-t
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 8G
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: iomp-t-consul-pv
