apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        BUILD_ID: "69"
        JOB_BASE_NAME: iomp-analysis-deploy-test
        app.cpaas.io/name: analysis.iomp-s1
        cpaasAutoDeploy: "10"
    name: analysis-iomp-s1-analysis
    namespace: iomp-s1
spec:
    replicas: 2
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-analysis-iomp-s1-analysis
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                BUILD_ID: "69"
                JOB_BASE_NAME: iomp-analysis-deploy-test
                app: deployment-analysis-iomp-s1-analysis
                app.cpaas.io/name: analysis.iomp-s1
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-analysis-iomp-s1-analysis
                version: v1
        spec:
            containers:
                - env:
                    - name: ACTIVE_PROFILES
                      value: s1
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                  image: harbor.ms.io/iomp-s1/iomp-s1-analysis:20201116_01
                  imagePullPolicy: Always
                  livenessProbe:
                    failureThreshold: 5
                    httpGet:
                        path: /analysis/health
                        port: 18096
                        scheme: HTTP
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    timeoutSeconds: 30
                  name: iomp-s1-analysis
                  readinessProbe:
                    failureThreshold: 5
                    httpGet:
                        path: /analysis/health
                        port: 18096
                        scheme: HTTP
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    timeoutSeconds: 30
                  resources:
                    limits:
                        cpu: "1"
                        memory: 2Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /iomp/iomp/files
                      name: file-volume
                      subPath: analysis
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-s1-consul-0.register-c1-s1-consul.iomp-s1.svc.appk8s.acp.as.io register-c2-s1-consul-0.register-c2-s1-consul.iomp-s1.svc.appk8s.acp.as.io register-c3-s1-consul-0.register-c3-s1-consul.iomp-s1.svc.appk8s.acp.as.io
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                    - name: CONSUL_DATACENTER_SET
                      value: as|as-dc=register-c1-s1-consul-0.register-c1-s1-consul.iomp-s1.svc.appk8s.acp.as.io;bs|bs-dc=register-c1-s1-consul-0.register-c1-s1-consul.iomp-s1.svc.appk8s.acp.bs.io
                  image: harbor.ms.io/common-s1/s1-consul:20200831_01
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 8301
                    timeoutSeconds: 30
                  name: s1-consul
                  readinessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 8301
                    timeoutSeconds: 30
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
                - name: dockercfg--iomp--iomp-harbor-devops-copy
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: file-volume
                  persistentVolumeClaim:
                    claimName: file-volume
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: analysis.iomp-s1
        cpaasAutoDeploy: "10"
        jmx-monitor: app-jmx-monitor
        poin-monitor: app-poin-monitor
    name: analysis-iomp-s1-analysis
    namespace: iomp-s1
spec:
    ports:
        - name: tcp-18096-18096
          port: 18096
          protocol: TCP
          targetPort: 18096
        - name: tcp-8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: tcp-18080-18080
          port: 18080
          protocol: TCP
          targetPort: 18080
        - name: tcp-9091-9091
          port: 9091
          protocol: TCP
          targetPort: 9091
    selector:
        service.cpaas.io/name: deployment-analysis-iomp-s1-analysis
    sessionAffinity: None
    type: ClusterIP
