apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    finalizers:
        - kubernetes.io/pvc-protection
    labels:
        cpaasAutoDeploy: "10"
    name: file-volume
    namespace: iomp-d
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1G
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: iomp-d-file-pv
