apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: mysql-production.iomp-t
        cpaasAutoDeploy: "10"
    name: mysql-production
    namespace: iomp-t
spec:
    ports:
        - port: 3309
          protocol: TCP
          targetPort: 3309
    sessionAffinity: None
    type: ClusterIP
