apiVersion: v1
kind: Endpoints
metadata:
    labels:
        app.cpaas.io/name: mysql-production.iomp-d
        cpaasAutoDeploy: "10"
    name: mysql-production
    namespace: iomp-d
subsets:
    - addresses:
        - ip: 10.200.127.133
      ports:
        - port: 3309
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: mysql-production.iomp-d
        cpaasAutoDeploy: "10"
    name: mysql-production
    namespace: iomp-d
spec:
    ports:
        - port: 3309
          protocol: TCP
          targetPort: 3309
    sessionAffinity: None
    type: ClusterIP
