apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        BUILD_ID: "8"
        JOB_BASE_NAME: iomp-poincenter-deploy
        app.cpaas.io/name: poin-manage-center.iomp-d
        cpaasAutoDeploy: "10"
    name: poin-manage-center-iomp-d-poincenter
    namespace: iomp-d
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-poin-manage-center-iomp-d-poincenter
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                BUILD_ID: "8"
                JOB_BASE_NAME: iomp-poincenter-deploy
                app: deployment-poin-manage-center-iomp-d-poincenter
                app.cpaas.io/name: poin-manage-center.iomp-d
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-poin-manage-center-iomp-d-poincenter
                version: v1
        spec:
            containers:
                - env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: ACTIVE_PROFILES
                      value: dev
                    - name: __FILE_LOG_PATH__
                      value: /iomp/iomp/jarweb/wlslogs/poin-sysmodulelog.log
                  image: harbor.td.io/iomp-d/iomp-d-poincenter:latest
                  imagePullPolicy: IfNotPresent
                  name: iomp-d-poincenter
                  resources:
                    limits:
                        cpu: "2"
                        memory: 4G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-d-consul register-c2-d-consul register-c3-d-consul
                  image: harbor.td.io/common-d/d-consul:20200721_01
                  imagePullPolicy: IfNotPresent
                  name: d-consul
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
                - name: dockercfg--iomp--iomp-harbor-devops-copy
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
