apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        BUILD_ID: "11"
        JOB_BASE_NAME: iomp-process-deploy
        app.cpaas.io/name: process.iomp-d
        cpaasAutoDeploy: "10"
    name: process-iomp-process
    namespace: iomp-d
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-process-iomp-process
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                BUILD_ID: "6"
                JOB_BASE_NAME: iomp-process-deploy
                app: deployment-process-iomp-process
                app.cpaas.io/name: process.iomp-d
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-process-iomp-process
                version: v1
        spec:
            containers:
                - env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: ACTIVE_PROFILES
                      value: dev
                    - name: __FILE_LOG_PATH__
                      value: /iomp/iomp/jarweb/wlslogs/poin-sysmodulelog.log
                  image: harbor.td.io/iomp-d/iomp-process:latest
                  imagePullPolicy: Always
                  name: iomp-process
                  resources:
                    limits:
                        cpu: "1"
                        memory: 2Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /iomp/iomp/files
                      name: file-volume
                      subPath: process
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-d-consul register-c2-d-consul register-c3-d-consul
                  image: harbor.td.io/common-d/d-consul:20200721_01
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 8301
                    timeoutSeconds: 30
                  name: d-consul
                  readinessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 8301
                    timeoutSeconds: 30
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
                - name: dockercfg--iomp--iomp-harbor-devops-copy
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: file-volume
                  persistentVolumeClaim:
                    claimName: file-volume
