apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: zipkin.iomp-d
        cpaasAutoDeploy: "10"
    name: zipkin-zipkin
    namespace: iomp-d
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-zipkin-zipkin
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                app: deployment-zipkin-zipkin
                app.cpaas.io/name: zipkin.iomp-d
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-zipkin-zipkin
                version: v1
        spec:
            containers:
                - image: harbor.td.io/iomp-d/zipkin:20200902_01
                  imagePullPolicy: IfNotPresent
                  name: zipkin
                  resources:
                    limits:
                        cpu: "1"
                        memory: 2Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-d-consul register-c2-d-consul register-c3-d-consul
                  image: harbor.td.io/common-d/d-consul:20200721_01
                  imagePullPolicy: IfNotPresent
                  name: d-consul
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: zipkin.iomp-d
        cpaasAutoDeploy: "10"
    name: zipkin
    namespace: iomp-d
spec:
    ports:
        - name: tcp-9411-9411
          port: 9411
          protocol: TCP
          targetPort: 9411
        - name: tcp-8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
    selector:
        service.cpaas.io/name: deployment-zipkin-zipkin
    sessionAffinity: None
    type: ClusterIP
