apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        BUILD_ID: "7"
        JOB_BASE_NAME: iomp-poincenter-deploy-test
        app.cpaas.io/name: poin-manage-center.iomp-t
        cpaasAutoDeploy: "10"
    name: poin-manage-center-iomp-t-poincenter
    namespace: iomp-t
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-poin-manage-center-iomp-t-poincenter
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                BUILD_ID: "7"
                JOB_BASE_NAME: iomp-poincenter-deploy-test
                app: deployment-poin-manage-center-iomp-t-poincenter
                app.cpaas.io/name: poin-manage-center.iomp-t
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-poin-manage-center-iomp-t-poincenter
                version: v1
        spec:
            containers:
                - env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: ACTIVE_PROFILES
                      value: test
                  image: harbor.td.io/iomp-t/iomp-t-poincenter:latest
                  imagePullPolicy: IfNotPresent
                  name: iomp-t-poincenter
                  resources:
                    limits:
                        cpu: "2"
                        memory: 4G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-t-consul register-c2-t-consul register-c3-t-consul
                  image: harbor.td.io/common-t/t-consul:20200721_01
                  imagePullPolicy: IfNotPresent
                  name: t-consul
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
                - name: dockercfg--iomp--iomp-harbor-devops-copy
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: poin-manage-center.iomp-t
        cpaasAutoDeploy: "10"
    name: iomp-t-poincenter
    namespace: iomp-t
spec:
    ports:
        - name: 8033-8033
          port: 8033
          protocol: TCP
          targetPort: 8033
        - name: 9090-9090
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: 9411-9411
          port: 9411
          protocol: TCP
          targetPort: 9411
        - name: 8500-8500
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: 8301-8301
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: 8501-8501
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: 8302-8302
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: 8300-8300
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: 8502-8502
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: 8600-8600
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: 10007-10007
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: 10008-10008
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        service.cpaas.io/name: deployment-poin-manage-center-iomp-t-poincenter
    sessionAffinity: None
    type: ClusterIP
