apiVersion: v1
kind: Endpoints
metadata:
    labels:
        app.cpaas.io/name: mysql-production.iomp-p
        cpaasAutoDeploy: "10"
    name: mysql-production
    namespace: iomp-p
subsets:
    - addresses:
        - ip: 10.1.53.166
      ports:
        - port: 16315
          protocol: TCP
