apiVersion: v1
kind: Endpoints
metadata:
    labels:
        app.cpaas.io/name: gauss-dev.iomp-s2
        cpaasAutoDeploy: "10"
    name: gauss-dev
    namespace: iomp-s2
subsets:
    - addresses:
        - ip: 10.200.60.33
      ports:
        - port: 25308
          protocol: TCP


