apiVersion: apps/v1
kind: StatefulSet
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        app.cpaas.io/name: register-c1.iomp-s2
        cpaasAutoDeploy: "10"
    name: register-c1-s2-consul
    namespace: iomp-s2
spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: statefulset-register-c1-s2-consul
    serviceName: register-c1-s2-consul
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                app: statefulset-register-c1-s2-consul
                app.cpaas.io/name: register-c1.iomp-s2
                project.cpaas.io/name: iomp
                service.cpaas.io/name: statefulset-register-c1-s2-consul
                version: v1
        spec:
            containers:
                - env:
                    - name: CONSUL_START_MODEL
                      value: s
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: CONSUL_DATACENTER_SET
                      value: as|as-dc=register-c1-s2-consul-0.register-c1-s2-consul.iomp-s2.svc.appk8s.acp.as.io;bs|bs-dc=register-c1-s2-consul-0.register-c1-s2-consul.iomp-s2.svc.appk8s.acp.bs.io
                    - name: CONSUL_AGENT_OPTION
                      value: -retry-join-wan=register-c2-s2-consul-0.register-c2-s2-consul.iomp-s2.svc.appk8s.acp.bs.io -retry-join-wan=register-c3-s2-consul-0.register-c3-s2-consul.iomp-s2.svc.appk8s.acp.bs.io
                  image: harbor.ms.io/common-s2/s2-consul:20200831_01
                  imagePullPolicy: IfNotPresent
                  name: s2-consul
                  resources:
                    limits:
                        cpu: "1"
                        memory: 2Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /consul/datacenter
                      name: consul-volume
                      subPath: as-c1-datadir
                    - mountPath: /consul/log
                      name: consul-volume
                      subPath: as-c1-log
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: consul-volume
                  persistentVolumeClaim:
                    claimName: consul-s2ev
    updateStrategy:
        rollingUpdate:
            partition: 0
        type: RollingUpdate
