apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00297
        ncp/internal_ip_for_policy: 100.64.131.67
    labels:
        cpaasAutoDeploy: "10"
    name: ftp-gateway-lb
    namespace: iomp-ftp-s1
spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: l4lb-bs-appk8s-acp-iomp-ftp-s1-gateway-205.172-ippool
    ports:
        - name: tcp-19090-19090
          nodePort: 31331
          port: 19090
          protocol: TCP
          targetPort: 19090
        - name: tcp-10007-10007
          nodePort: 31568
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: tcp-10008-10008
          nodePort: 30627
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        app: deployment-ftp-gateway-ftp-gateway
        app.cpaas.io/name: ftp-gateway.iomp-ftp-s1
        project.cpaas.io/name: iomp
        service.cpaas.io/name: deployment-ftp-gateway-ftp-gateway
        version: v1
    sessionAffinity: None
    type: LoadBalancer
