apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00297
    labels:
        app.cpaas.io/name: ftp-ui.iomp-ftp-d
        cpaasAutoDeploy: "10"
    name: ftp-ui-ftp-ui
    namespace: iomp-ftp-d
spec:
    replicas: 1
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-ftp-ui-ftp-ui
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00297
            labels:
                app: deployment-ftp-ui-ftp-ui
                app.cpaas.io/name: ftp-ui.iomp-ftp-d
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-ftp-ui-ftp-ui
                version: v1
        spec:
            containers:
                - image: harbor.td.io/iomp-d/ftp-ui:20201027_03
                  imagePullPolicy: IfNotPresent
                  name: ftp-ui
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1Gi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
