apiVersion: v1
kind: Service
metadata:
    annotations:
        cpaas.io/creator: k00395
        ncp/error.loadbalancer: IP_POOL_NOT_FOUND
    labels:
        cpaasAutoDeploy: "10"
        poin-monitor: app-poin-monitor
    name: poin-gateway-lb
    namespace: iomp-s2
spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: l4lb-as-appk8s-acp-iomp-s2-gateway-254.181-ippool
    ports:
        - name: tcp-9090-9090
          nodePort: 31098
          port: 9090
          protocol: TCP
          targetPort: 9090
        - name: tcp-8500-8500
          nodePort: 31928
          port: 8500
          protocol: TCP
          targetPort: 8500
        - name: tcp-8501-8501
          nodePort: 32459
          port: 8501
          protocol: TCP
          targetPort: 8501
        - name: tcp-8502-8502
          nodePort: 32692
          port: 8502
          protocol: TCP
          targetPort: 8502
        - name: tcp-8600-8600
          nodePort: 32632
          port: 8600
          protocol: TCP
          targetPort: 8600
        - name: tcp-8300-8300
          nodePort: 30763
          port: 8300
          protocol: TCP
          targetPort: 8300
        - name: tcp-8301-8301
          nodePort: 30655
          port: 8301
          protocol: TCP
          targetPort: 8301
        - name: tcp-8302-8302
          nodePort: 32446
          port: 8302
          protocol: TCP
          targetPort: 8302
        - name: tcp-10007-10007
          nodePort: 32581
          port: 10007
          protocol: TCP
          targetPort: 10007
        - name: tcp-10008-10008
          nodePort: 30466
          port: 10008
          protocol: TCP
          targetPort: 10008
    selector:
        service.cpaas.io/name: deployment-poin-gateway-iomp-s2-gateway
    sessionAffinity: None
    type: LoadBalancer
