apiVersion: v1
kind: Endpoints
metadata:
    labels:
        app.cpaas.io/name: mysql-production.iomp-s2
        cpaasAutoDeploy: "10"
    name: mysql-production
    namespace: iomp-s2
subsets:
    - addresses:
        - ip: 10.233.147.50
      ports:
        - port: 16315
          protocol: TCP
