apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        app.cpaas.io/last-replicas: "0"
        cpaas.io/creator: k00395
    labels:
        BUILD_ID: "7"
        JOB_BASE_NAME: iomp-poincenter-deploy-test
        app.cpaas.io/name: poin-manage-center.iomp-s2
        cpaasAutoDeploy: "10"
    name: poin-manage-center-iomp-s2-poincenter
    namespace: iomp-s2
spec:
    replicas: 2
    selector:
        matchLabels:
            project.cpaas.io/name: iomp
            service.cpaas.io/name: deployment-poin-manage-center-iomp-s2-poincenter
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations:
                cpaas.io/creator: k00395
            labels:
                BUILD_ID: "7"
                JOB_BASE_NAME: iomp-poincenter-deploy-test
                app: deployment-poin-manage-center-iomp-s2-poincenter
                app.cpaas.io/name: poin-manage-center.iomp-s2
                project.cpaas.io/name: iomp
                service.cpaas.io/name: deployment-poin-manage-center-iomp-s2-poincenter
                version: v1
        spec:
            containers:
                - env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: ACTIVE_PROFILES
                      value: s2
                  image: harbor.ms.io/iomp-s2/s2-iomp-poincenter:20201116_01
                  imagePullPolicy: Always
                  livenessProbe:
                    failureThreshold: 5
                    httpGet:
                        path: /poin/health
                        port: 8033
                        scheme: HTTP
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    timeoutSeconds: 30
                  name: iomp-s2-poincenter
                  readinessProbe:
                    failureThreshold: 5
                    httpGet:
                        path: /poin/health
                        port: 8033
                        scheme: HTTP
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    timeoutSeconds: 30
                  resources:
                    limits:
                        cpu: "2"
                        memory: 4G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                - env:
                    - name: CONSUL_RETRY_JOIN_ADDR
                      value: register-c1-s2-consul-0.register-c1-s2-consul.iomp-s2.svc.appk8s.acp.as.io register-c2-s2-consul-0.register-c2-s2-consul.iomp-s2.svc.appk8s.acp.as.io register-c3-s2-consul-0.register-c3-s2-consul.iomp-s2.svc.appk8s.acp.as.io
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: status.podIP
                    - name: MY_POD_NAME
                      valueFrom:
                        fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                    - name: CONSUL_DATACENTER_SET
                      value: as|as-dc=register-c1-s2-consul-0.register-c1-s2-consul.iomp-s2.svc.appk8s.acp.as.io;bs|bs-dc=register-c1-s2-consul-0.register-c1-s2-consul.iomp-s2.svc.appk8s.acp.bs.io
                  image: harbor.ms.io/common-s2/s2-consul:20200831_01
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 8301
                    timeoutSeconds: 30
                  name: s2-consul
                  readinessProbe:
                    failureThreshold: 5
                    initialDelaySeconds: 300
                    periodSeconds: 60
                    successThreshold: 1
                    tcpSocket:
                        port: 8301
                    timeoutSeconds: 30
                  resources:
                    limits:
                        cpu: "1"
                        memory: 1G
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: dockercfg--iomp--iomp-harbor
                - name: dockercfg--iomp--iomp-harbor-devops-copy
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
